name: 'Changelog'
description: 'Detects changes and validates a given changelog'
inputs:
  token:
    description: 'GitHub token'
    required: true
  sources:
    description: 'Comma separated string with the folders to check'
    default: '*'
  ignoreActionLabel:
    description: 'Label to avoid executing the action'
    required: false
    default: '-Changelog'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: check-square
  color: green
