name: 'Changelog Validator'
description: 'Detects changes and validates a given changelog'
inputs:
  token:
    description: 'GitHub token'
    required: true
  changelogs: 
    description: 'Array with all Changelogs in the project'
    required: true
  modifiedFiles:
    description: 'Array with all modified files'
    reequired: true
runs:
  using: 'node12'
  main: 'src/index.js'
