name: Test
on: [pull_request]

jobs:
  lint:
    name: Statics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # Uses an action in the root directory
        with:
          token: ${{github.token}}

